### ISSUE TITLE
npm run build not building anymore ?

### ISSUE THREAD

**Issue by brunofunnie** [KELiON/cerebro-converter#12]
I'm trying to build the current master but it's returning empty at the dist/ directory. Is anyone having the same behavior ?

> bruno@brdlbnogueira: /projects/cerebro-converter$ npm run build
> 
> cerebro-converter@1.0.5 build /home/bruno/projects/cerebro-converter
> cerebro-scripts build
> 
> Building Cerebro plugin into /home/bruno/projects/cerebro-converter/dist
>     Bundling all files...
>     Done! Your plugin is ready to publish
> bruno@brdlbnogueira: /projects/cerebro-converter$ ls -la dist/
> total 8
> drwxr-xr-x 2 bruno bruno 4096 dez 19 11:24 .
> drwxr-xr-x 6 bruno bruno 4096 dez 19 11:24 ..
> bruno@brdlbnogueira: /projects/cerebro-converter$

Node: v8.9.3
NPM: 5.6.0

**Comment by KELiON** [comment]
@brunofunny interesting, for me everything is ok. Can you try to `rm -rf ./node_modules && yarn && yarn build`?

**Comment by brunofunnie** [comment]
Works fine with Yarn, thanks!
