### ISSUE TITLE
Add Chilean pesos (CLP)

### ISSUE THREAD

**Issue by cncastillo** [KELiON/cerebro-converter#7]
Hi! I love the plugin. Could you add Chilean pesos (CLP) to the supported currencies?

**Comment by KELiON** [comment]
Done, @cncastillo!

**Comment by cncastillo** [comment]
Hi thanks! it has a weird problem when my default country is Chile (in Cerebro settings) if I do:
`120 usd in clp => 120$ = 80,000clp `
If it's not the default (i.e. United Kingdom):
`120 usd in clp => 120$ = 79,930.26clp`
I don't know why the setting difference make the values to round up :(
