### ISSUE TITLE
Currency conversion is not working anymore

### ISSUE THREAD

**Issue by max-baz** [KELiON/cerebro-converter#9]
It's happening for a few days now, Cerebro is not showing any output for queries like "10 usd in eur". There's nothing in the console as well. Perhaps the service used by the plugin is not responding, or changed format of their API.

**Comment by KELiON** [comment]
@maximbaz something happened with yahoo API that we use, it always returns empty results, for example this url (https://query.yahooapis.com/v1/public/yql?q=select+*+from+yahoo.finance.xchange+where+pair+=+%22USDEUR%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=) returns

```
{"query":{"count":0,"created":"2017-11-09T08:31:24Z","lang":"en-GB","results":null}}
```

I'll try to find what happened, maybe they changed format of `pair` column

**Comment by max-baz** [comment]
I've accidentally come across this post. I guess it's time to find a replacement for yahoo 🙂

![image](https://user-images.githubusercontent.com/1177900/33231028-49dfb14e-d1ee-11e7-8ddd-3cbda0114d9e.png)

**Comment by KELiON** [comment]
Ok, any suggestions of good and free currency conversion API?)

**Comment by max-baz** [comment]
Not really, but I'm following a similar topic on a different tool which also broke due to yahoo being discontinued, I'll let you know if they find something interesting - ping me if you find something as well so that I can share 🙂

**Comment by brunofunnie** [comment]
Does http://fixer.io/ looks reliable ?

**Comment by max-baz** [comment]
That's awesome finding @brunofunny! 

```
$ http 'https://api.fixer.io/latest?base=USD&symbols=DKK'

{
    "base": "USD",
    "date": "2017-12-18",
    "rates": {
        "DKK": 6.3111
    }
}
```

**Comment by max-baz** [comment]
That was quick, awesome :)

**Comment by KELiON** [comment]
@maximbaz yep, but I don't understand why it doesn't work in published version, when everything is ok locally) Checking it now

**Comment by KELiON** [comment]
Ok, now it works:) Thanks everyone!

**Comment by max-baz** [comment]
Someone found another API, thought I'd post it here in case we find issues with fixer.io:

http://www.mycurrency.net/page/Free+Currency+Converter+API

**Comment by max-baz** [comment]
Fixer.io only has 31 currencies and updates exchange rate once a day, we should switch to mycurrency.net, which provides 176 currencies and refreshes exchange rate every 2 hours - #13

**Comment by Marlinekhavele** [comment]
how can I cache an API and make it work both offline and online

**Comment by ajithkumar-natarajan** [comment]
This plugin doesn't seem to work anymore for me. Tried uninstalling and reinstalling. Does it work for others?
